// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/bloc_test/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/domain/users_model.dart' as _i5;
import 'package:frontend/infrastructure/user/users_repository.dart' as _i3;
import 'package:frontend/infrastructure/user/users_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsersService_0 extends _i1.SmartFake implements _i2.UsersService {
  _FakeUsersService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UsersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRepository extends _i1.Mock implements _i3.UsersRepository {
  MockUsersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UsersService get userService => (super.noSuchMethod(
        Invocation.getter(#userService),
        returnValue: _FakeUsersService_0(
          this,
          Invocation.getter(#userService),
        ),
      ) as _i2.UsersService);

  @override
  _i4.Future<List<_i5.User>> fetchUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
      ) as _i4.Future<List<_i5.User>>);

  @override
  _i4.Future<void> changeStatus(dynamic user) => (super.noSuchMethod(
        Invocation.method(
          #changeStatus,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
